# Copy file as config.toml, fill with info
# Get your access token from https://magicboard.monday.com/apps/manage/tokens
api_access_token = "eyJhbGciOi..."

# Get your user ID from your profile (bottom-left corner of Monday interface)
# https://magicboard.monday.com/users/...
logging_user_id = "123456789"
