# Run `mlog u` to fetch the latest version of this file.

# For users to know which config they have downloaded
description = 'Board configuration covering months August 2023 to March 2024 (updated on 2024-06-25)'

# These column IDs are needed to populate the "person" and "hours" field
# They appear to be stable month-to-month
person_column_id = 'person7'
hours_column_id = 'hours7'

# Idea is to accept a logms date as yyyy-mm-dd and split in two: ["yyyy-mm", "-dd"]
# 1. Locate the relevant month to query the correct board
# 2. Locate the correct day to know which group to interact with

# Previous months - Imll backfill day-to-group mappings if they're needed.
[months.2023-05]
board_id = '4387022645'

[months.2023-06]
board_id = '4547507308'

[months.2023-07]
board_id = '4721697359'

# Full boards configuration starting at August 2023
[months.2023-08]
board_id = '4925671275'
name = 'Aug 2023 :Completed Work'

[months.2023-08.days]
'-01' = 'tue_aug_01'
'-02' = 'wed_aug_02'
'-03' = 'thu_aug_03'
'-04' = 'fri_aug_04'
'-05' = 'sat_aug_05'
'-06' = 'sun_aug_06'
'-07' = 'mon_aug_07'
'-08' = 'tue_aug_08'
'-09' = 'wed_aug_09'
'-10' = 'thu_aug_10'
'-11' = 'fri_aug_11'
'-12' = 'sat_aug_12'
'-13' = 'sun_aug_13'
'-14' = 'mon_aug_14'
'-15' = 'tue_aug_15'
'-16' = 'wed_aug_16'
'-17' = 'thu_aug_17'
'-18' = 'fri_aug_18'
'-19' = 'sat_aug_19'
'-20' = 'sun_aug_20'
'-21' = 'mon_aug_21'
'-22' = 'tue_aug_22'
'-23' = 'wed_aug_23'
'-24' = 'thu_aug_24'
'-25' = 'fri_aug_25'
'-26' = 'sat_aug_26'
'-27' = 'sun_aug_27'
'-28' = 'mon_aug_28'
'-29' = 'tue_aug_29'
'-30' = 'wed_aug_30'
'-31' = 'thu_aug_31'

[months.2023-09]
board_id = '5064273451'
name = 'Sep 2023 :Completed Work'

[months.2023-09.days]
'-01' = 'fri_sep_01'
'-02' = 'sat_sep_02'
'-03' = 'sun_sep_03'
'-04' = 'mon_sep_04'
'-05' = 'tue_sep_05'
'-06' = 'wed_sep_06'
'-07' = 'thu_sep_07'
'-08' = 'fri_sep_08'
'-09' = 'sat_sep_09'
'-10' = 'sun_sep_10'
'-11' = 'mon_sep_11'
'-12' = 'tue_sep_12'
'-13' = 'wed_sep_13'
'-14' = 'thu_sep_14'
'-15' = 'fri_sep_15'
'-16' = 'sat_sep_16'
'-17' = 'sun_sep_17'
'-18' = 'mon_sep_18'
'-19' = 'tue_sep_19'
'-20' = 'wed_sep_20'
'-21' = 'duplicate_of_fri_sep_22'
'-22' = 'fri_sep_22'
'-23' = 'sat_sep_23'
'-24' = 'sun_sep_24'
'-25' = 'mon_sep_25'
'-26' = 'tue_sep_26'
'-27' = 'wed_sep_27'
'-28' = 'thu_sep_28'
'-29' = 'fri_sep_29'
# No group for Sept 30th
#'Group 1' = 'new_group36'

[months.2023-10]
board_id = '5262708320'
name = 'Oct 2023 :Completed Work'

[months.2023-10.days]
'-01' = 'fri_sep_01'
'-02' = 'sat_sep_02'
'-03' = 'sun_sep_03'
'-04' = 'mon_sep_04'
'-05' = 'tue_sep_05'
'-06' = 'wed_sep_06'
'-07' = 'thu_sep_07'
'-08' = 'fri_sep_08'
'-09' = 'sat_sep_09'
'-10' = 'sun_sep_10'
'-11' = 'mon_sep_11'
'-12' = 'tue_sep_12'
'-13' = 'wed_sep_13'
'-14' = 'thu_sep_14'
'-15' = 'fri_sep_15'
'-16' = 'sat_sep_16'
'-17' = 'sun_sep_17'
'-18' = 'mon_sep_18'
'-19' = 'tue_sep_19'
'-20' = 'wed_sep_20'
'-21' = 'duplicate_of_fri_sep_22'
'-22' = 'fri_sep_22'
'-23' = 'sat_sep_23'
'-24' = 'sun_sep_24'
'-25' = 'mon_sep_25'
'-26' = 'tue_sep_26'
'-27' = 'wed_sep_27'
'-28' = 'thu_sep_28'
'-29' = 'fri_sep_29'
'-30' = 'new_group'
'-31' = 'new_group91955'

[months.2023-11]
board_id = '5263793809'
name = 'Nov 2023 :Completed Work'

[months.2023-11.days]
'-01' = 'wed_nov_01'
'-02' = 'thu_nov_02'
'-03' = 'fri_nov_03'
'-04' = 'sat_nov_04'
'-05' = 'sun_nov_05'
'-06' = 'mon_nov_06'
'-07' = 'tue_nov_07'
'-08' = 'wed_nov_08'
'-09' = 'thu_nov_09'
'-10' = 'fri_nov_10'
'-11' = 'sat_nov_11'
'-12' = 'sun_nov_12'
'-13' = 'mon_nov_13'
'-14' = 'tue_nov_14'
'-15' = 'wed_nov_15'
'-16' = 'thu_nov_16'
'-17' = 'fri_nov_17'
'-18' = 'sat_nov_18'
'-19' = 'sun_nov_19'
'-20' = 'mon_nov_20'
'-21' = 'tue_nov_21'
'-22' = 'wed_nov_22'
'-23' = 'thu_nov_23'
'-24' = 'fri_nov_24'
'-25' = 'sat_nov_25'
'-26' = 'sun_nov_26'
'-27' = 'mon_nov_27'
'-28' = 'tue_nov_28'
'-29' = 'wed_nov_29'
'-30' = 'thu_nov_30'
# Extra unnecessary column?
#'Group 1' = 'new_group36'

[months.2023-12]
board_id = '5611241888'
name = 'Dec 2023 :Completed Work'

[months.2023-12.days]
'-01' = 'fri_dec_01'
'-02' = 'sat_dec_02'
'-03' = 'sun_dec_03'
'-04' = 'mon_dec_04'
'-05' = 'tue_dec_05'
'-06' = 'wed_dec_06'
'-07' = 'thu_dec_07'
'-08' = 'fri_dec_08'
'-09' = 'sat_dec_09'
'-10' = 'sun_dec_10'
'-11' = 'mon_dec_11'
'-12' = 'tue_dec_12'
'-13' = 'wed_dec_13'
'-14' = 'thu_dec_14'
'-15' = 'fri_dec_15'
'-16' = 'sat_dec_16'
'-17' = 'sun_dec_17'
'-18' = 'mon_dec_18'
'-19' = 'tue_dec_19'
'-20' = 'wed_dec_20'
'-21' = 'thu_dec_21'
'-22' = 'fri_dec_22'
'-23' = 'sat_dec_23'
'-24' = 'sun_dec_24'
'-25' = 'mon_dec_25'
'-26' = 'tue_dec_26'
'-27' = 'wed_dec_27'
'-28' = 'thu_dec_28'
'-29' = 'fri_dec_29'
# Extra unnecessary column?
#'Group 1' = 'new_group36'

[months.2024-01]
board_id = '5741140241'
name = 'Jan 2024 :Completed Work'

[months.2024-01.days]
'-01' = 'mon_jan_01'
'-02' = 'tue_jan_02'
'-03' = 'wed_jan_03'
'-04' = 'thu_jan_04'
'-05' = 'fri_jan_05'
'-06' = 'sat_jan_06'
'-07' = 'sun_jan_07'
'-08' = 'mon_jan_08'
'-09' = 'tue_jan_09'
'-10' = 'wed_jan_10'
'-11' = 'thu_jan_11'
'-12' = 'fri_jan_12'
'-13' = 'sat_jan_13'
'-14' = 'sun_jan_14'
'-15' = 'mon_jan_15'
'-16' = 'tue_jan_16'
'-17' = 'wed_jan_17'
'-18' = 'thu_jan_18'
'-19' = 'fri_jan_19'
'-20' = 'sat_jan_20'
'-21' = 'sun_jan_21'
'-22' = 'mon_jan_22'
'-23' = 'tue_jan_23'
'-24' = 'wed_jan_24'
'-25' = 'thu_jan_25'
'-26' = 'fri_jan_26'
'-27' = 'sat_jan_27'
'-28' = 'sun_jan_28'
'-29' = 'mon_jan_29'
'-30' = 'tue_jan_30'
'-31' = 'wed_jan_31'

[months.2024-02]
board_id = '5933594503'
name = 'Feb 2024 :Completed Work'

[months.2024-02.days]
'-01' = 'thu_feb_01'
'-02' = 'fri_feb_02'
'-03' = 'sat_feb_03'
'-04' = 'sun_feb_04'
'-05' = 'mon_feb_05'
'-06' = 'tue_feb_06'
'-07' = 'wed_feb_07'
'-08' = 'thu_feb_08'
'-09' = 'fri_feb_09'
'-10' = 'sat_feb_10'
'-11' = 'sun_feb_11'
'-12' = 'mon_feb_12'
'-13' = 'tue_feb_13'
'-14' = 'wed_feb_14'
'-15' = 'thu_feb_15'
'-16' = 'fri_feb_16'
'-17' = 'sat_feb_17'
'-18' = 'sun_feb_18'
'-19' = 'mon_feb_19'
'-20' = 'tue_feb_20'
'-21' = 'wed_feb_21'
'-22' = 'thu_feb_22'
'-23' = 'fri_feb_23'
'-24' = 'sat_feb_24'
'-25' = 'sun_feb_25'
'-26' = 'mon_feb_26'
'-27' = 'tue_feb_27'
'-28' = 'wed_feb_28'
'-29' = 'thu_feb_29'

[months.2024-03]
board_id = '6132068436'
name = 'Mar 2024 :Completed Work'

[months.2024-03.days]
'-01' = 'fri_mar_01'
'-02' = 'sat_mar_02'
'-03' = 'sun_mar_03'
'-04' = 'mon_mar_04'
'-05' = 'tue_mar_05'
'-06' = 'wed_mar_06'
'-07' = 'thu_mar_07'
'-08' = 'fri_mar_08'
'-09' = 'sat_mar_09'
'-10' = 'sun_mar_10'
'-11' = 'mon_mar_11'
'-12' = 'tue_mar_12'
'-13' = 'wed_mar_13'
'-14' = 'thu_mar_14'
'-15' = 'fri_mar_15'
'-16' = 'sat_mar_16'
'-17' = 'sun_mar_17'
'-18' = 'mon_mar_18'
'-19' = 'tue_mar_19'
'-20' = 'wed_mar_20'
'-21' = 'thu_mar_21'
'-22' = 'fri_mar_22'
'-23' = 'sat_mar_23'
'-24' = 'sun_mar_24'
'-25' = 'mon_mar_25'
'-26' = 'tue_mar_26'
'-27' = 'wed_mar_27'
'-28' = 'thu_mar_28'
'-29' = 'fri_mar_29'
'-30' = 'new_group'
